### ISSUE TITLE
Compatibility with VS2019 or VSCode (C/C++)

### ISSUE THREAD

**Issue by VanitarNordic** [littlevgl/lv_sim_visual_studio_sdl#5]
Hi,

does the repo compatible with Visual Studio 2019 or VSCode with C/C++ complie possibility?

**Comment by embeddedt** [comment]
Visual Studio Code does not ship with its own compiler, so I doubt that it can build and run the project. However, opening the project and browsing/editing files might work, as I think it can open Visual Studio projects (but not build them).

I do not use standard Visual Studio for anything but [this page](https://docs.microsoft.com/en-us/visualstudio/porting/port-migrate-and-upgrade-visual-studio-projects?view=vs-2019) might help you. I assume that it's backwards compatible, so opening the project in VS2019 will probably work.
