### ISSUE TITLE
When adding C++ classes we are unable to compile

### ISSUE THREAD

**Issue by mvturnho** [littlevgl/lv_sim_visual_studio_sdl#6]
When adding C++ class files the project can not be compiled. You have to set the project properties to do so by setting compile as to default.

![image](https://user-images.githubusercontent.com/2076073/76504719-89c47d00-6448-11ea-93c8-62b4a9e929de.png)

But then when you compile lvgl is generating compile errors;
![image](https://user-images.githubusercontent.com/2076073/76504803-ac569600-6448-11ea-926e-9a69a6b336c6.png)

When removing the C++ classes and setting the compiler back to Compile as C Code (/TC) it all compiles and runs fine.
![image](https://user-images.githubusercontent.com/2076073/76504905-d60fbd00-6448-11ea-9c36-fb7482191eef.png)

How can I solve this and combine my C++ classes with lvgl in visual studio?

**Comment by embeddedt** [comment]
First, you need to compile the LittlevGL files as C code and your C++ classes as C++ code. I'm not sure if you are doing this already.

Then you will most likely run into the fact that Visual Studio's C++ compiler has [issues](https://stackoverflow.com/questions/33270731/error-c4576-in-vs2015-enterprise) with one of the initializer constructs used in LittlevGL. This issue has been reported before in #2; the solution there was to switch to a different IDE which includes a compiler with support for this construct.

**Comment by Triangulix** [comment]
Hi
I would like to use LV in an Arduino project which is C++ but also use the simulator to have a quicker way for creating the UI.

Is there a viable way to use the simulator together with C++ code in Visual Studio? Maybe creating 2 projects and referencing the C project from the C++ project?
Or should I forget the idea and go without the simulator?

Thanks

**Comment by kisvegabor** [comment]
Take a look at the [platform_io](https://github.com/littlevgl/lv_platformio/) project. Hope it helps.

**Comment by Triangulix** [comment]
Thanks, but I now went for writing my own object oriented GUI system.

**Comment by kisvegabor** [comment]
Okay, good luck with your project!

**Comment by embeddedt** [comment]
Fixed by https://github.com/lvgl/lvgl/pull/1711 (will be released with 7.4).
